---
- name: reload nfs exports
  command: exportfs -ra

- name: restart phone-home receiver
  ansible.builtin.systemd:
    name: phone-home-receiver.service
    state: restarted
    daemon_reload: true

- name: restart apt-cacher-ng
  ansible.builtin.systemd:
    name: apt-cacher-ng
    state: restarted
